name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'wordpress-bedrock/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'wordpress-bedrock/**'
  workflow_dispatch:
  repository_dispatch:
    types: [docker_webhook]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            tags: |
              fydron/wordpress-bedrock:latest
          - dockerfile: Dockerfile.dev
            tags: fydron/wordpress-bedrock:development-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./wordpress-bedrock
          file: ./wordpress-bedrock/${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker Hub Description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: fydron/wordpress-bedrock
          readme-filepath: ./wordpress-bedrock/README.md

  # Adds logs to dicord channel
  notify:
      needs: build-and-push
      runs-on: ubuntu-latest
      if: always()
      steps:
        - name: Get Commit Name
          run: echo "THREAD_ID=1317127197961490514" >> $GITHUB_OUTPUT

        - name: Notify Discord
          uses: tsickert/discord-webhook@v6.0.0
          with:
            webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
            thread-id: ${{ env.THREAD_ID }}
            embed-title: "WordPress Bedrock Build Notification"
            embed-description: |
              **Build Status:** ${{ needs.build-and-push.result == 'success' && '✅ Success' || '❌ Failure' }}

              **Workflow Details:**
              - Repository: ${{ github.repository }}
              - Branch: ${{ github.ref_name }}
              - Commit: ${{ github.sha }}
              - Triggered By: ${{ github.actor }}
            embed-color: ${{ needs.build-and-push.result == 'success' && '3066993' || '15158332' }}
            content: |
              Build notification for WordPress Bedrock Docker images
